const theme = {
     colors: {
          primary: '#7E1B75',
          primaryLight: '#F1D4F6',
          secondary: '#222222',
          tertiary: '#323232',
          success: '#28a745',
          danger: '#dc3545',
          warning: '#ffc107',
          info: '#17a2b8',
          light: '#EEEEEE',
          dark: '#343a40',

          lighterGrey: '#8f8f8f',
          white: '#FFFFFF',
          lighterBlue: '#E4FCFA',
          black: '#000',
     },
     fonts: {
          primary: 'Roboto, sans-serif',
          secondary: 'Open Sans, sans-serif',
          display: 'Montserrat, sans-serif',
          body: 'Noto Sans, sans-serif',
     },
     fontWeights: {
          light: '100',
          semiLight: '300',
          semiBold: '400',
          mediumSemiBold: '600',
          bold: '800',
     },
     fontSizes: {
          verysmall: '0.7rem',
          smallest: '1rem',
          small: '1.5rem',
          mediumSmall: '2rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
          bigBig: '8rem',
     },
     spacing: {
          smallest: '1rem',
          small: '2rem',
          mediumSmall: '3rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
     },
     height: {
          smallest: '1rem',
          small: '2rem',
          mediumSmall: '3rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
          bigBig: '8rem',
     },
};

export default theme;
